// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudProvider } from "./CloudProvider";

/**
 * A cloud model for the choice in Settings.
 */
export type CloudModelOption = { provider: CloudProvider, id: string, name: string, };
