// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadPhase } from "./DownloadPhase";

export type DownloadStatus = { phase: DownloadPhase, downloaded: number, 
/**
 * User-facing reason when the download failed.
 */
error: string | null, };
