// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineStatus = { "state": "idle" } | { "state": "loading", model: string, } | { "state": "ready", model: string, } | { "state": "failed", model: string, };
