// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the AI model runs. Cloud is used only after the user chooses it.
 */
export type InferenceMode = "local" | "cloud";
