// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Interaction = { id: number, 
/**
 * Milliseconds since the Unix epoch.
 */
createdAt: number, request: string, response: string, results: Array<string>, awaitingConfirmation: boolean, };
