// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A microphone the user can choose in Settings.
 */
export type MicrophoneOption = { id: string, name: string, };
