// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStatus } from "./DownloadStatus";

export type ModelInfo = { id: string, name: string, quantization: string, size: number, recommended: boolean, warning: string | null, 
/**
 * The model plus its context may not fit in the memory available right now.
 */
memoryWarning: boolean, installed: boolean, active: boolean, download: DownloadStatus | null, };
