// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudProvider } from "./CloudProvider";
import type { InferenceMode } from "./InferenceMode";

export type Settings = { 
/**
 * Empty until the user connects Home Assistant.
 */
homeAssistantUrl: string, 
/**
 * Changed only by selecting an installed model, never by saving the form.
 */
activeModel: string | null, contextLength: number, 
/**
 * Changed only from the listening control, never by saving the form.
 */
listening: boolean, wakeWord: string, 
/**
 * A voice id from the catalogue.
 */
voice: string, 
/**
 * Changed only from the Local and Cloud control, never by saving the form.
 */
inference: InferenceMode, cloudProvider: CloudProvider, openaiModel: string, anthropicModel: string, };
