// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { 
/**
 * Empty until the user connects Home Assistant.
 */
homeAssistantUrl: string, ollamaUrl: string, model: string, contextLength: number, };
