// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { 
/**
 * Empty until the user connects Home Assistant.
 */
homeAssistantUrl: string, 
/**
 * Changed only by selecting an installed model, never by saving the form.
 */
activeModel: string | null, contextLength: number, 
/**
 * Changed only from the listening control, never by saving the form.
 */
listening: boolean, wakeWord: string, };
