// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionStatus } from "./ConnectionStatus";
import type { EngineStatus } from "./EngineStatus";
import type { VoiceStatus } from "./VoiceStatus";

export type Status = { homeAssistant: ConnectionStatus, engine: EngineStatus, voice: VoiceStatus, };
