// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStatus } from "./DownloadStatus";

export type VoiceModelsInfo = { installed: boolean, size: number, download: DownloadStatus | null, };
