// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A voice Luna can speak with, for the choice in Settings.
 */
export type VoiceOption = { id: string, name: string, accent: string, };
