// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceState } from "./VoiceState";

export type VoiceStatus = { state: VoiceState, 
/**
 * Why listening is off when the user wanted it on.
 */
problem: string | null, };
